name: worldclock
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2
  intl: ^0.19.0
  flutter_spinkit: ^5.2.1
  postgresql2: ^1.7.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
 

flutter:
  uses-material-design: true

  assets:
    - assets/bg.jpg
    - assets/usa.png
    - assets/uk.png
    - assets/tokyo.png
    - assets/south_korea.png
    - assets/singapore.webp
    - assets/qatar.webp
    - assets/newyork.png
    - assets/kenya.png
    - assets/jerusalem.png
    - assets/indonesia.png
    - assets/greece.png
    - assets/germany.png
    - assets/egypt.png
    - assets/dubai.png
    - assets/colombo.webp
    - assets/bangkok.png
    - assets/hongkong.jpg
    - assets/perth.png
    - assets/melbourne.png
    - assets/sydney.png
    - assets/rome.jpeg
    - assets/jamaica.jpg
    - assets/mexico.png
    - assets/toronto.png
    - assets/vancouver.png
    - assets/dublin.jpg


    

  fonts:
    - family: SignikaNegative
      fonts:
        - asset: fonts/SignikaNegative-VariableFont_wght.ttf